version : "3.8"

services : 
  mysql :
    image: mysql:8
    container_name : rate_limiter_mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ratelimiter
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data: